- name: Ansible Playbook to Install and Setup a webserver on Ubuntu
  hosts: webservers
  become: true
  tasks:
    - name: Install latest version of Apache
      ansible.builtin.apt: 
          name=apache2 
          state=latest
 
    - name: Copy your index file
      template:
        src: "index.html.j2"
        dest: "/var/www/html/index.html"
        mode: 0644
 
    - name: Modify apache2 config to listen on port 8080
      lineinfile:
        dest: /etc/apache2/ports.conf
        regexp: "^Listen 80"
        line: "Listen 8080"
        state: present
 
    - name: modify default config to listen to port 8080
      lineinfile:
        dest: /etc/apache2/sites-enabled/000-default.conf
        regexp: '^VirtualHost \*:80>'
        line: '<VirtualHost *:8080>'
        state: present
 
    - name: startd and enable apache2
      service:
        name: apache2
        enabled: true
        state: started
 
