---
-  hosts: webservers
   become: true
   
   tasks:
    - name: stop apache2 server
      service:
        name: apache2
        state: stopped
    - name: uninstall apache2
      ansible.builtin.apt:
        name: apache2
        state: absent     
